//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSureFileUpload.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileUploads
    {
        public long FileID { get; set; }
        public long PetID { get; set; }
        public string FileType { get; set; }
        public string FileName { get; set; }
        public string OriginalFileName { get; set; }
    
        public virtual Pets Pets { get; set; }
    }
}
