//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetSureFileUpload.WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pets
    {
        public Pets()
        {
            this.FileUploads = new HashSet<FileUploads>();
        }
    
        public long PetID { get; set; }
        public string Name { get; set; }
        public bool Enable { get; set; }
    
        public virtual ICollection<FileUploads> FileUploads { get; set; }
    }
}
